name: SonarCloud Analysis

on:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    continue-on-error: true

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: agprueba
          MYSQL_USER: user
          MYSQL_PASSWORD: user
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Docker-Compose
        uses: docker/setup-compose-action@v1

      - name: Execute All Services
        run: docker compose up -d
          
      - name: Build and test Authorization Server
        run: | 
          cd authorization-server 
          mvn -B clean verify

      - name: Build and test Resource Server
        run: | 
          cd resource-server
          mvn -B clean verify

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular dependencies
        run: |
          cd ag-prueba-front
          npm install

      - name: Test Angular with coverage
        run: |
          cd ag-prueba-front
          npm run test -- --watch=false --code-coverage

      - name: ESLint
        run: | 
          cd ag-prueba-front
          npm run lint -- --format json > eslint-report.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master